[package]
name = "plist"
version = "0.1.1"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Very much a work in progress."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist/"
documentation = "https://docs.rs/plist/0.1.1/plist/"
keywords = ["plist", "parser"]
build = "build.rs"

[features]
default = ["serde_serialization"]
serde_serialization = ["serde"]

[dependencies]
rustc-serialize = "0.3.19"
xml-rs = "0.3.8"
byteorder = "0.5.3"
chrono = "0.2.22"
serde = { version = "0.9.5", optional = true }

[dev-dependencies]
serde_derive = { version = "0.9.5" }
