[package]
name = "plist"
version = "0.5.0"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Supports Serde serialization."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist/"
documentation = "https://docs.rs/plist/0.5.0/plist/"
keywords = ["plist", "parser"]
categories = ["config", "encoding", "parser-implementations"]

[features]
default = ["serde"]

[dependencies]
base64 = "0.10.1"
byteorder = "1.3.0"
humantime = "1.1.1"
line-wrap = "0.1.1"
xml-rs = "0.8.0"
serde = { version = "1.0.2", optional = true }

[dev-dependencies]
serde_derive = { version = "1.0.2" }
