[package]
name = "plist"
version = "0.2.4"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Supports Serde serialization."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist/"
documentation = "https://docs.rs/plist/0.2.4/plist/"
keywords = ["plist", "parser"]
build = "build.rs"

[features]
default = ["serde"]

[dependencies]
base64 = "0.6.0"
byteorder = "1.0.0"
chrono = "0.4.0"
xml-rs = "0.6.1"
serde = { version = "1.0.2", optional = true }

[dev-dependencies]
serde_derive = { version = "1.0.2" }
