[package]
name = "plist"
version = "0.3.0"
authors = ["Ed Barnard <eabarnard@gmail.com>"]
description = "A rusty plist parser. Supports Serde serialization."
license = "MIT"
repository = "https://github.com/ebarnard/rust-plist/"
documentation = "https://docs.rs/plist/0.3.0/plist/"
keywords = ["plist", "parser"]
build = "build.rs"

[features]
default = ["serde"]

[dependencies]
base64 = "0.9.0"
byteorder = "1.1.0"
humantime = "1.1.1"
xml-rs = "0.7.0"
serde = { version = "1.0.2", optional = true }

[dev-dependencies]
serde_derive = { version = "1.0.2" }
